---
title: "DarwnCore Alignment in Neotoma"
author: "Simon Goring, Jack Williams, Mark Uhen, Michael McLennan"
date: "July 10, 2016"
output: html_document
---

<style type="text/css">
table {
   padding: 0;border-collapse: collapse; 
   layout: fixed; 
   width: 100%; }
table tr {
   border-top: 1px solid #cccccc;
   background-color: white;
   margin: 0;
   padding: 0; }
table tr:nth-child(2n) {
   background-color: #f8f8f8; }
table tr th {
   font-weight: bold;
   border: 1px solid #cccccc;
   margin: 0;
   padding: 6px 13px; }
table tr td {
   border: 1px solid #cccccc;
   margin: 0;
   padding: 6px 13px; }
table tr th :first-child, table tr td :first-child {
   margin-top: 0; }
table tr th :last-child, table tr td :last-child {
   margin-bottom: 0; }
</style>

# DwC Alignment:

The Neotoma Paleoecological database represents a rich source of data to researchers and the public who may be interested in biodiversity, biogeography and temporal and spatial ecology at long time scales.  The data crosses multiple allied disciplines, from archaeology, geography, biology, paleontology, ecology and, primarily, paleoecology.  The breadth of utility for this data is potentially hampered by the reliance on a single source of access for the data.

To broaden the availability of data from Netoma, we are working with the Global Biodiversity Information Facility (GBIF).  GBIF is an international organization that partners with a number of organizations to make biodiversity data available online.  The use of clear metadata standards, like DarwinCore, make GBIF a useful resource, and the increased size of the data holdings further improve its utility for researchers working on global biodiversity research.

There are three key steps in making Neotoma data available through GBIF.  The first is mapping Neotoma data holdings and concepts onto the metadata standards within GBIF.  This current document is based on [key metadata terms provided by DarwinCore](http://rs.tdwg.org/dwc/terms/), and the ways in which the can represent Neotoma data, across dataset types.  In cases where the current implementation of DarwinCore (or other existing metadata standards such as DublinCore) fails to represent important concepts within Neotoma, we describe new terms that can be used to supplement existing metadata.

The second step is simply scraping the Neotoma Database, both at the dataset level for the initial push, but then secondarily, keeping GBIF up-to-date with Neotoma holdings.

The last step is to ensure that content matches in an ongoing manner.  In all cases, the flow chart is essentially similar:

<embed src="images/DwC_Upload.svg" type="image/svg+xml" />

To then undertake the mapping of the records, we build a `csv` file for upload, from each individual record within Neotoma using the following mapping:

## Record Level Terms

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
| * | `"Dataset"` | [`dcterms:type`](http://rs.tdwg.org/dwc/terms/index.htm#dcterms:type) | The nature or genre of the resource. For Darwin Core, recommended best practice is to use the name of the class that defines the root of the record. |
| * | `Datasets:RecDateModified` | [`dcterms:modified`](http://rs.tdwg.org/dwc/terms/index.htm#dcterms:modified) | The most recent date-time on which the resource was changed. For Darwin Core, recommended best practice is to use an encoding scheme, such as ISO 8601:2004(E). |
| * | `"en-US"`  | dcterms:language | A language of the resource. Recommended best practice is to use a controlled vocabulary such as RFC 4646 [RFC4646]. |
| * | [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/deed.en_US) | dcterms:license | |
| * | `Contacts:ContactName` | dcterms:rightsHolder | A person or organization owning or managing rights over the resource. |
| * | `"public"` | dcterms:accessRights | Information about who can access the resource or an indication of its security status. |
| * | `DatasetPublications:Citation` | dcterms:bibliographicCitation | A bibliographic reference for the resource as a statement indicating how this record should be cited (attributed) when used. Recommended practice is to include sufficient bibliographic detail to identify the resource as unambiguously as possible. |
| * | submission date | gbif:year | The year of data submission. |
| * | Explorer link | `dcterms:references` | A related resource that is referenced, cited, or otherwise pointed to by the described resource. |
|   | IGSNs for samples? | institutionID | An identifier for the institution having custody of the object(s) or information referred to in the record. |
| * | `AnalysisUnitID:AnalysisUnits`| collectionID | An identifier for the collection or dataset from which the record was derived. |
| * | `DatasetID:Datasets` | datasetID | |
|   | `RepositoryInstitutions:Acronym` | institutionCode | The name (or acronym) in use by the institution having custody of the object(s) or information referred to in the record. |
|  | | collectionCode | |
| * | `"Neotoma Dataset *n*"` | datasetName | |
|  | | ownerInstitutionCode | |
|  | | basisOfRecord | The specific nature of the data record. |
|  | | informationWithheld | Additional information that exists, but that has not been shared in the given record. |
|  | | dataGeneralizations | Actions taken to make the shared data less specific or complete than in its original form. Suggests that alternative data of higher quality may be available on request. |
|  | | dynamicProperties | 	A list of additional measurements, facts, characteristics, or assertions about the record. Meant to provide a mechanism for structured content. JSON structured: "{"thing":value}" |

## Organism

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
| * | `AnalysisUnits:AnalysisUnitID` + `TaxonID` | occurrenceID | |
|  | | catalogNumber | |
|  | | recordNumber | |
| * | `DatasetPI` or `Contacts:ContactName` | recordedBy | Could also be the dataset PI |
|  | Pollen grains are not individuals, could work with `MNI` counts | individualCount | |
|  | | organismQuantity | |
|  | | organismQuantityType | |
|  | | sex | |
|  | | lifeStage | |
|  | | reproductiveCondition | |
|  | | behavior | |
|  | | establishmentMeans | |
| * | `present` | occurrenceStatus | A statement about the presence or absence of a Taxon at a Location. Recommended best practice is to use a controlled vocabulary. |
|  | | preparations | |
|  | | disposition | |
|  | | associatedMedia | |
| * | `Publications:Citation` pipe separated | associatedReferences | |
|  | | associatedSequences | |
| * | `"cooccurrs with: "` | associatedTaxa | A list (concatenated and separated) of identifiers or names of taxa and their associations with the Occurrence. |
|  | | otherCatalogNumbers | |
|  |  | occurrenceRemarks | Comments or notes about the Occurrence. |

## Organism

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
|  | | organismID | |
|  | | organismName | | 
|  | | organismScope |  |
| * | Same as `associatedTaxa`, but with Occurrence IDs |  associatedOccurrences | A list (concatenated and separated) of identifiers of other Occurrence records and their associations to this Occurrence. |
|  | |  associatedOrganisms | A list (concatenated and separated) of identifiers of other Organisms and their associations to this Organism. |
|  | |  previousIdentifications | |
|  | |  organismRemarks | |

## MaterialSample, LivingSpecimen, PreservedSpecimen, FossilSpecimen

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
|  | IGSN | materialSampleID | | 

## Event, HumanObservation, MachineObservation

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
| * | `AnalysisUnitID` | eventID | |
| * | `CollectionUnitID` | parentEventID | |
|  | | fieldNumber | |
| * | `CollectionUnits:CollDate` | eventDate | The date-time or interval during which an Event occurred. | 
|  | | eventTime | |
| * | `1` | startDayOfYear | |
| * | `365` or `366`| endDayOfYear |  |
| * | get year from `CollectionUnits:CollDate` | year | |
| * | get month from `CollectionUnits:CollDate` | month | |
| * | get day from `CollectionUnits:CollDate` | day | |
|  | | verbatimEventDate | |
|  | | habitat | |
| * | `Datasets:datasettype` | samplingProtocol | |
| * | `Data:value` | sampleSizeValue | |
| * | `VariableUnits:VariableUnit` | sampleSizeUnit | |
|  | Total count for the analysis unit | samplingEffort | |
| | | fieldNotes | One of a) an indicator of the existence of, b) a reference to (publication, URI), or c) the text of notes taken in the field about the Event. |
| * | `CollectionUnits:Notes` | eventRemarks | |

## Location

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
|  | | locationID | | 
| * | `GeopoliticalUnits` | higherGeographyID | | 
| * | `GeopoliticalUnits` | higherGeography | | 
|  | | continent | | 
|  | | waterBody | | 
|  | | islandGroup | | 
|  | | island | | 
| * | `GeoPoliticalUnits:GeoPoliticalName` | country | |
| * | `GeopoliticalUnits` | countryCode | |
| * | `GeopoliticalUnits` | stateProvince | | 
|  | | county | | 
|  | | municipality | | 
|  | | locality | | 
|  | | verbatimLocality | | 
|  | `Sites:Altitude` | minimumElevationInMeters | | 
|  | `Sites:Altitude` | maximumElevationInMeters | | 
|  | | verbatimElevation | | 
|  | | minimumDepthInMeters | | 
|  | | maximumDepthInMeters | | 
|  | | verbatimDepth | | 
|  | | minimumDistanceAboveSurfaceInMeters | | 
|  | | maximumDistanceAboveSurfaceInMeters | | 
|  | | locationAccordingTo | | 
| * | `Sites:SiteDescription` | locationRemarks | |
| * | `Sites:LongitudeEast` | decimalLatitude | |
| * | `Sites:LatitudeNorth` | decimalLongitude | |
| * | `EPSG:4326` | geodeticDatum | |
|  | | coordinateUncertaintyInMeters | |
| * | `max(c(Sites:LongitudeEast - Sites:LongitudeWest,` \n `Sites:LatitudeNorth - Sites:LatitudeSouth))` | coordinatePrecision | A decimal representation of the precision of the coordinates given in the decimalLatitude and decimalLongitude. |
|  | | pointRadiusSpatialFit | |
|  | | verbatimCoordinates | |
|  | | verbatimLatitude | |
|  | | verbatimLongitude | |
|  | | verbatimCoordinateSystem | |
|  | | verbatimSRS | |
| * | e.g., `POLYGON ((10 20, 11 20, 11 21, 10 21, 10 20))` | footprintWKT | |
| * | `EPSG:4326` | footprintSRS | |
|  | | footprintSpatialFit | |
| * | `DatasetPI` | georeferencedBy | |
|  | | georeferencedDate | |
|  | | georeferenceProtocol | |
|  | | georeferenceSources | |
|  | | georeferenceVerificationStatus | |
|  | | georeferenceRemarks | |

## GeologicalContext

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
|  | | geologicalContextID | |
| * | `"Phanerozoic"` | earliestEonOrLowestEonothem | |
| * | `"Phanerozoic"` | latestEonOrHighestEonothem | |
| * | `"Cenozoic"` | earliestEraOrLowestErathem | |
| * | `"Cenozoic"` | latestEraOrHighestErathem | |
| * | `"Quaternary"` - but check | earliestPeriodOrLowestSystem | | 
| * | `"Quaternary"` - but check | latestPeriodOrHighestSystem | |
| * | `"Holocene"` or `"Pleistocene"` - but check | earliestEpochOrLowestSeries | |
| * | `"Holocene"` or `"Pleistocene"` - but check | latestEpochOrHighestSeries | |
| * | Ages in the Holocene are geographically constrained, but we have relative ages. | earliestAgeOrLowestStage | |
| * | Ages in the Holocene are geographically constrained, but we have relative ages. | latestAgeOrHighestStage | The full name of the latest possible geochronologic age or highest chronostratigraphic stage attributable to the stratigraphic horizon from which the cataloged item was collected. |
|  | | lowestBiostratigraphicZone | |
|  | | highestBiostratigraphicZone | |
|  | `Lithology:Description` | lithostratigraphicTerms |  **Note**: This is complicated, you need to find depth & lithographic terms.|
|  | | group | |
|  | | formation | |
|  | | member | |
|  | | bed | |

## Identification

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
|  | | identificationID | |
|  | regex search for key qualifiers (*e.g.*, ?, cf, type) | identificationQualifier | A brief phrase or a standard term ("cf.", "aff.") to express the determiner's doubts about the Identification. |
|  | | typeStatus | |
| * | `DatasetPI` | identifiedBy | |
|  | | dateIdentified | |
|  | | identificationReferences | |
|  | | identificationVerificationStatus | |
|  | | identificationRemarks | |

## Taxon

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
|  | | taxonID | An identifier for the set of taxon information (data associated with the Taxon class). May be a global unique identifier or an identifier specific to the data set. |
|  | `Taxa:TaxonID` | scientificNameID | An identifier for the nomenclatural (not taxonomic) details of a scientific name. |
|  | | acceptedNameUsageID | |
|  | | parentNameUsageID | |
|  | | originalNameUsageID | |
|  | | nameAccordingToID | |
| * | `Taxa:PublicationID` | namePublishedInID | |
|  | | taxonConceptID | |
| * | `Taxa:TaxonName` | scientificName | The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the identificationQualifier term. |
|  | | acceptedNameUsage | |
|  | | parentNameUsage | |
|  | | originalNameUsage | |
|  | | nameAccordingTo | | 
|  | | namePublishedIn | | 
|  | | namePublishedInYear | | 
|  | | higherClassification | | 
|  | | kingdom | |
|  | | phylum | | 
|  | | class | | 
|  | | order | |
|  | | family | |
|  | | genus | | 
|  | | subgenus | | 
|  | | specificEpithet | |  
|  | | infraspecificEpithet | | 
|  | | taxonRank | | 
|  | | verbatimTaxonRank | | 
| * | `Taxa:Author` | scientificNameAuthorship | The authorship information for the scientificName formatted according to the conventions of the applicable nomenclaturalCode. |
|  | |  vernacularName | | 
|  | | nomenclaturalCode | | 
|  | | taxonomicStatus | | 
|  | | nomenclaturalStatus | | 
|  | | taxonRemarks | | 

## Auxiliary Terms
### MeasurementOrFact

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
| | measurementID | | 
| | measurementType | | 
| | measurementValue | | 
| | measurementAccuracy | | 
| | measurementUnit | | 
| | measurementDeterminedBy | | 
| | measurementDeterminedDate | | 
| | measurementMethod | | 
| | measurementRemarks| | 

### ResourceRelationship

| Implemented | Neotoma | DarwinCore | Description |
| ----------- | ------- | ---------- | ---------- |
| | resourceRelationshipID | | 
| | resourceID | | 
| | relatedResourceID | | 
| | relationshipOfResource | | 
| | relationshipAccordingTo | | 
| | relationshipEstablishedDate | | 
| | relationshipRemarks| | 
